# General
live_config_reload = true

import = ["~/.config/alacritty/theme.toml"]

[window]
title = "ForAeons"
decorations = "Full"
opacity = 0.8
blur = true
startup_mode = "Maximized"
dynamic_padding = true

[font]
size = 14
normal = { "family" = "FiraCode Nerd Font Mono", style = "Regular" }
bold = { "family" = "FiraCode Nerd Font Mono", style = "Bold" }

[keyboard]
bindings = [
  { key = "ArrowLeft", mods = "Control|Shift", action = "SelectPreviousTab" },
  { key = "ArrowRight", mods = "Control|Shift", action = "SelectNextTab" },
]
