# General
live_config_reload = true

# Theme
import = ["~/.config/alacritty/theme.toml"]

# Window
[window]
decorations = "Full"
opacity = 0.9
blur = true
startup_mode = "Maximized"

# Font
[font]
size = 14
normal = { "family" = "FiraCode Nerd Font Mono" }
