# General
live_config_reload = true

# Color theme
import = ["~/.config/alacritty/theme.toml"]

[env]
TERM = "xterm-256color"

[window]
title = "ForAeons"
dimensions = { columns = 120, lines = 36 }
decorations = "Full"
opacity = 0.8
blur = true
startup_mode = "Windowed"
dynamic_padding = true

[font]
size = 16
normal = { "family" = "Iosevka Nerd Font Mono", style = "Regular" }
bold = { "family" = "Iosevka Nerd Font Mono", style = "Bold" }
italic = { "family" = "Iosevka Nerd Font Mono", style = "Italic" }
bold_italic = { "family" = "Iosevka Nerd Font Mono", style = "Bold Italic" }

[keyboard]
bindings = [
  { key = "ArrowLeft", mods = "Control|Shift", action = "SelectPreviousTab" },
  { key = "ArrowRight", mods = "Control|Shift", action = "SelectNextTab" },
]
